// pgRDF Console — root app component.

const { useState: useStateA, useMemo: useMemoA } = React;

const SAMPLE_SPARQL = `PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ub:   <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>

# Find professors teaching courses that some grad student takes.
# Designed visually — auto-generated from the canvas above.
SELECT ?prof ?name ?course ?student
WHERE {
  ?prof    a            ub:Professor       .
  ?prof    ub:teacherOf ?course            .
  ?course  a            ub:Course          .
  ?student a            ub:GraduateStudent .
  ?student ub:takesCourse ?course          .
  OPTIONAL { ?student ub:advisor ?prof }   .
  ?prof    foaf:name    ?name              .
  FILTER ( STRLEN(?name) > 0 )
}
ORDER BY ?prof
LIMIT 500`;

const SAMPLE_SQL = `-- Generated by pgRDF query planner — cached as plan pgrdf_q_2f9c
PREPARE pgrdf_q_2f9c (bigint, bigint, bigint, bigint, bigint) AS
WITH bgp AS (
  SELECT  q1.subject_id AS prof,
          q1.object_id  AS course_via_teaches,
          q3.subject_id AS student,
          q5.object_id  AS name
  FROM       _pgrdf_quads q0  -- ?prof a ub:Professor
        JOIN _pgrdf_quads q1 USING (subject_id)        -- ub:teacherOf
        JOIN _pgrdf_quads q2 ON q2.subject_id = q1.object_id
        JOIN _pgrdf_quads q3 ON q3.object_id  = q1.object_id  -- takesCourse
        JOIN _pgrdf_quads q4 ON q4.subject_id = q3.subject_id -- a GraduateStudent
        JOIN _pgrdf_quads q5 ON q5.subject_id = q1.subject_id -- foaf:name
  WHERE  q0.predicate_id = $1 AND q0.object_id    = $2
    AND  q1.predicate_id = $3
    AND  q2.predicate_id = $1 AND q2.object_id    = $4
    AND  q3.predicate_id = $5
    AND  q4.predicate_id = $1 AND q4.object_id    = $6
)
SELECT  pgrdf_dict_resolve(prof),
        pgrdf_dict_resolve(name),
        pgrdf_dict_resolve(course_via_teaches),
        pgrdf_dict_resolve(student)
FROM bgp
ORDER BY prof
LIMIT 500;

EXECUTE pgrdf_q_2f9c (8401, 11827, 8412, 11842, 11831, 11910);`;

const DEFAULT_SPARQL = `PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ub:   <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>

# Live query — runs against this project's pgRDF database.
# Edit freely and press Run (or ⌘↵).
SELECT ?name ?course
WHERE {
  ?prof a ub:FullProfessor ;
        foaf:name    ?name ;
        ub:teacherOf ?c .
  ?c    foaf:name    ?course .
}
ORDER BY ?name`;

function App() {
  const [t, setTweak] = useTweaks(TWEAK_DEFAULTS);
  const [mode, setMode] = useStateA("visual");
  const [view, setView] = useStateA("query");
  const [active, setActive] = useStateA({ graph: 1, saved: "q1" });
  const [selected, setSelected] = useStateA("prof");
  const [nodes, setNodes] = useStateA(window.PGRDF_DATA.Q_NODES);
  const [bottomH, setBottomH] = useStateA(220);

  // ── live query state ──────────────────────────────────────────────
  const [sparql, setSparql]   = useStateA(DEFAULT_SPARQL);
  const [result, setResult]   = useStateA(null);   // {cols,rows,count,ms,error}
  const [running, setRunning] = useStateA(false);
  const [bottomTab, setBottomTab] = useStateA("sparql");
  const slug = window.PGRDF_PROJECT || "demo";

  const runQuery = async () => {
    setRunning(true);
    setBottomTab("results");
    const t0 = performance.now();
    try {
      const res = await fetch(`/p/${slug}/api/query`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "Accept": "application/json" },
        body: JSON.stringify({ sparql }),
      });
      const ms = Math.round(performance.now() - t0);
      const body = await res.json();
      if (!res.ok) {
        setResult({ cols: [], rows: [], count: 0, ms, error: body.detail || `HTTP ${res.status}` });
      } else {
        setResult({ cols: body.cols || [], rows: body.rows || [], count: body.count || 0, ms, error: null });
      }
    } catch (e) {
      setResult({ cols: [], rows: [], count: 0, ms: Math.round(performance.now() - t0), error: String(e) });
    } finally {
      setRunning(false);
    }
  };

  React.useEffect(() => {
    const onKey = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") { e.preventDefault(); runQuery(); }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [sparql]);

  const onMove = (id, x, y) => {
    setNodes(ns => ns.map(n => n.id === id ? { ...n, x, y } : n));
  };

  const dbStats = window.PGRDF_DATA.dbStats || {
    triples:  "2.4M",
    inferred: "312K",
    dict:     "184K",
    cache:    "94.2%",
  };

  // Apply tweaks to root vars
  React.useEffect(() => {
    const root = document.documentElement;
    const accents = {
      blue:    ["#2f6fb0", "#e7f0fa", "#b9d3ec"],
      graphite:["#0e0e0e", "#ededec", "#cfcfcd"],
      violet:  ["#5b3aa6", "#f1ecfa", "#d9c9ee"],
      teal:    ["#1f6f7a", "#e3f3f4", "#b9d9dc"],
    };
    const a = accents[t.accent] || accents.blue;
    root.style.setProperty("--accent", a[0]);
    root.style.setProperty("--accent-soft", a[1]);
    root.style.setProperty("--accent-line", a[2]);
    root.setAttribute("data-density", t.density);

    if (t.mono === "jetbrains") root.style.setProperty("--mono", `"JetBrains Mono", ui-monospace, monospace`);
    else if (t.mono === "ibm")  root.style.setProperty("--mono", `"IBM Plex Mono", ui-monospace, monospace`);
    else if (t.mono === "berkeley") root.style.setProperty("--mono", `"Berkeley Mono", "IBM Plex Mono", ui-monospace, monospace`);
  }, [t]);

  const mainView = (() => {
    if (view === "predicates") return <PredicatesView active={active}/>;
    if (view === "classes")    return <ClassesView active={active}/>;
    if (view === "shapes")     return <ShapesView active={active}/>;
    if (view === "rules")      return <RulesView active={active}/>;
    if (view === "graph")      return mode === "visual"
      ? <Canvas nodes={nodes} edges={window.PGRDF_DATA.Q_EDGES} onMove={onMove}
                selected={selected} setSelected={setSelected} nodeStyle={t.nodeStyle}/>
      : <GraphsView active={active}/>;
    // default — query workspace
    return <Canvas nodes={nodes} edges={window.PGRDF_DATA.Q_EDGES} onMove={onMove}
                   selected={selected} setSelected={setSelected} nodeStyle={t.nodeStyle}/>;
  })();

  const viewLabel = {
    query: "query workspace",
    graph: "named graph",
    classes: "classes",
    predicates: "predicates",
    shapes: "SHACL shapes",
    rules: "inference rules",
  }[view];

  const conn = {
    project: slug,
    db:      window.PGRDF_DATA._live ? (window.PGRDF_DATA.project || slug) : "research_db",
    version: window.PGRDF_DATA.pgrdf_version || null,
    live:    !!window.PGRDF_DATA._live,
  };

  return (
    <div className="app">
      <TopBar onRun={runQuery} running={running} conn={conn}
              onExplain={() => {}} onSave={() => {}}/>
      <SubBar mode={mode} setMode={setMode} view={viewLabel} dbStats={dbStats}/>
      <Sidebar view={view} setView={setView} active={active} setActive={setActive}/>
      <div className="main">
        {mainView}
        <BottomPanel sparql={sparql} setSparql={setSparql} sql={SAMPLE_SQL}
                     result={result} running={running}
                     tab={bottomTab} setTab={setBottomTab}
                     height={bottomH} setHeight={setBottomH}/>
      </div>

      <TweaksPanel>
        <TweakSection label="Theme"/>
        <TweakColor label="Accent" value={t.accent}
          options={["blue","graphite","violet","teal"].map(k => ({
            blue: "#2f6fb0", graphite: "#0e0e0e", violet: "#5b3aa6", teal: "#1f6f7a"
          }[k]))}
          onChange={(hex) => {
            const map = { "#2f6fb0":"blue","#0e0e0e":"graphite","#5b3aa6":"violet","#1f6f7a":"teal" };
            setTweak("accent", map[hex] || "blue");
          }}/>
        <TweakRadio label="Density" value={t.density}
          options={["compact","regular","comfy"]}
          onChange={(v) => setTweak("density", v)}/>
        <TweakSection label="Visual designer"/>
        <TweakRadio label="Node shape" value={t.nodeStyle}
          options={["circle","pill","box"]}
          onChange={(v) => setTweak("nodeStyle", v)}/>
        <TweakSection label="Typography"/>
        <TweakSelect label="Mono font" value={t.mono}
          options={["jetbrains","ibm","berkeley"]}
          onChange={(v) => setTweak("mono", v)}/>
      </TweaksPanel>
    </div>
  );
}

const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "accent": "blue",
  "density": "regular",
  "nodeStyle": "circle",
  "mono": "jetbrains"
}/*EDITMODE-END*/;

// ---- bootstrap: fetch live snapshot, then mount ----
// The project slug comes from ?project=<slug> (default "demo", the public
// tier). data.jsx already populated window.PGRDF_DATA with fixtures; we
// merge the live snapshot OVER them so keys the API doesn't supply yet
// (Q_NODES, Q_EDGES, PLAN_ROWS, LOG_ROWS) keep working.
(async function bootstrap() {
  const slug = new URLSearchParams(location.search).get("project") || "demo";
  window.PGRDF_PROJECT = slug;
  const fixtures = window.PGRDF_DATA || {};
  try {
    const res = await fetch(`/p/${slug}/api/snapshot`, { headers: { Accept: "application/json" } });
    if (res.ok) {
      const live = await res.json();
      window.PGRDF_DATA = { ...fixtures, ...live, _live: true };
      console.info(`pgRDF Console: live snapshot for project '${slug}' — ` +
                   `${(live.GRAPHS||[]).length} graphs, ${(live.CLASSES||[]).length} classes, ` +
                   `${(live.PREDICATES||[]).length} predicates`);
    } else {
      console.warn(`pgRDF Console: snapshot HTTP ${res.status} — using fixtures`);
      window.PGRDF_DATA = { ...fixtures, _live: false };
    }
  } catch (e) {
    console.warn("pgRDF Console: snapshot fetch failed — using fixtures", e);
    window.PGRDF_DATA = { ...fixtures, _live: false };
  }
  ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
})();
