PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ex: <http://example.org/book/>
PREFIX ns: <http://example.org/ns#>
SELECT ?title ?price
WHERE {
  ?book dc:title ?title .
  ?book ns:price ?price .
  VALUES ?book { ex:book1 ex:book3 }
}
