#!/usr/bin/env python3
"""Regenerate LATEST.md from the GHCR head of `ghcr.io/styk-tv/pgrdf-bundle`.

Called by `.github/workflows/update-latest-md.yml` AFTER SLSA Build Provenance
v1 attestation verification succeeds for the head digest(s). Re-renders the
whole LATEST.md every time — pgRDF ships a single OCI surface so there is no
"preserve the other side" logic the pgCK sibling renderer needs.

Env:
  VER                      pgRDF version (no ``v`` prefix; e.g. ``0.5.10``)
  GH_TOKEN                 GitHub token with ``packages:read``
  GITHUB_REPOSITORY_OWNER  GH owner slug (defaults to ``styk-tv``)

Output: full LATEST.md content on stdout.

Bootstrap discipline: this renderer trusts the workflow's `gh attestation
verify` step. v0.5.0–v0.5.9 will never be passed in as ``VER`` because their
digests do not verify — the workflow exits before reaching this renderer.
The bootstrap exception (PROVENANCE.md) is enforced upstream, not here.
"""

from __future__ import annotations

import datetime
import json
import os
import subprocess
import sys
from typing import Tuple


def gh_api(path: str) -> list[dict]:
    r = subprocess.run(
        ["gh", "api", path, "--paginate"],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(r.stdout)


def find_version(packages: list[dict], tag_filter: str) -> Tuple[str, str]:
    """Find the GHCR version whose tag list contains ``tag_filter``.

    Returns (digest, created_at_iso). Raises SystemExit if not found — that
    means the workflow's bookkeeping is wrong (asked us to render a VER for
    which no GHCR version exists).
    """
    for v in packages:
        tags = v.get("metadata", {}).get("container", {}).get("tags", [])
        if tag_filter in tags:
            digest = v["name"]
            if not digest.startswith("sha256:"):
                raise SystemExit(f"unexpected digest format: {digest}")
            return digest, v.get("created_at", "")
    raise SystemExit(f"no GHCR version found with tag {tag_filter!r}")


def fmt_ts(iso: str) -> str:
    return iso.replace("T", " ").replace("Z", "").split(".")[0]


def render(owner: str, ver: str) -> str:
    pkgs = gh_api(f"/users/{owner}/packages/container/pgrdf-bundle/versions")
    amd_d, amd_t = find_version(pkgs, f"{ver}-pg17-amd64")
    arm_d, arm_t = find_version(pkgs, f"{ver}-pg17-arm64")
    agg_d, _ = find_version(pkgs, ver)  # the bare ``X.Y.Z`` aggregate tag

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    return f"""<!--
  This file is auto-generated by .github/workflows/update-latest-md.yml after a
  successful oci-publish.yml run AND after SLSA Build Provenance v1
  attestations have been verified against every GHCR digest below. Do NOT edit
  by hand — the next workflow run will overwrite your changes. Last refresh:
  {now} (version: v{ver}).
-->

# pgRDF — latest published artifacts

One publishable surface ships from this repo: the PostgreSQL **extension** (oras-pulled OCI artifact). This file tracks the head on **PostgreSQL 17**. Older PG majors (14, 15, 16) are still built per release — see [Repo packages view](https://github.com/styk-tv/pgRDF/pkgs/container/pgrdf-bundle) for the full matrix.

## pgRDF extension — `v{ver}` (PostgreSQL 17)

Every digest below carries a verifiable SLSA Build Provenance v1 attestation per [`PROVENANCE.md`](./PROVENANCE.md). v0.5.0–v0.5.9 predate the attestation wiring and never appear here.

`oras pull ghcr.io/styk-tv/pgrdf-bundle:{ver}-pg17-<arch>` → drop `lib/pgrdf.so` + `share/extension/{{pgrdf.control, pgrdf--{ver}.sql}}` next to your `postgres:17` install.

| arch  | Pull URI                                             | Digest                                                                  | Created (UTC)       |
|-------|------------------------------------------------------|-------------------------------------------------------------------------|---------------------|
| amd64 | `ghcr.io/styk-tv/pgrdf-bundle:{ver}-pg17-amd64`     | `{amd_d}` | {fmt_ts(amd_t)} |
| arm64 | `ghcr.io/styk-tv/pgrdf-bundle:{ver}-pg17-arm64`     | `{arm_d}` | {fmt_ts(arm_t)} |

|                       |                                                                                                |
|-----------------------|------------------------------------------------------------------------------------------------|
| Artifact type         | `application/vnd.styk.pgrdf.bundle.v1+tar`                                                     |
| Aggregate index       | `ghcr.io/styk-tv/pgrdf-bundle:{ver}` (also tagged `v{ver}`)                                  |
| Aggregate digest      | `{agg_d}` |
| Provenance            | SLSA Build Provenance v1, Sigstore-backed, pushed as OCI referrer                              |
| Verify (CLI)          | `gh attestation verify oci://ghcr.io/styk-tv/pgrdf-bundle:{ver} --repo styk-tv/pgRDF`         |
| Tarball mirror        | https://github.com/styk-tv/pgRDF/releases/tag/v{ver}                                          |
| Repo packages view    | https://github.com/styk-tv/pgRDF/pkgs/container/pgrdf-bundle                                   |
| Older PG majors       | `{ver}-pg{{14,15,16}}-{{amd64,arm64}}` published alongside; same v{ver} tag; each individually attested |

## Verifying any artifact above

```sh
# Aggregate index (multi-arch, multi-PG-major)
gh attestation verify oci://ghcr.io/styk-tv/pgrdf-bundle:{ver} \\
  --repo styk-tv/pgRDF

# A specific PG×arch leaf
gh attestation verify oci://ghcr.io/styk-tv/pgrdf-bundle:{ver}-pg17-amd64 \\
  --repo styk-tv/pgRDF
```

A successful verify means: signed by GitHub's Fulcio CA against the OIDC token of the v{ver} `oci-publish` workflow run, recorded in Sigstore's Rekor transparency log, subject digest matches the pulled artifact.

## Pin policy

- There is **no `latest` synonym** on the extension OCI artifact — pin by `pg`×`arch` explicitly (e.g. `{ver}-pg17-amd64`).
- Tagged versions are immutable on GHCR.
- The aggregate `vX.Y.Z` / `X.Y.Z` index references all 8 per-PG×arch leaves for that release; pull it to let your client pick.
- Per [`PROVENANCE.md`](./PROVENANCE.md) Rule 2: do not consider an artifact "shipped" if its digest does not verify under `gh attestation verify`.

See [`CHANGELOG.md`](./CHANGELOG.md) and [`RELEASE_NOTES.md`](./RELEASE_NOTES.md) for what changed per version.
"""


def main() -> None:
    owner = os.environ.get("GITHUB_REPOSITORY_OWNER", "styk-tv")
    ver = os.environ.get("VER", "").strip()
    if not ver:
        raise SystemExit("VER environment variable is required (e.g. 0.5.10)")
    if ver.startswith("v"):
        ver = ver[1:]
    sys.stdout.write(render(owner, ver))


if __name__ == "__main__":
    main()
