//! `pgrdf.shacl_capability()` — which SHACL features `pgrdf.validate`
//! enforces, answerable as a query.
//!
//! Before this, that fact lived only in `tests/shacl-capability/CAPABILITY.json`,
//! a test artefact that does not ship. A consumer choosing shapes had to guess,
//! which is the same defect class as L7 (the interop digest every consumer had
//! reimplemented because the engine did not own the number) and L8 (a consumer
//! medicating against a defect for days after the fix shipped, because
//! "does this function exist" cannot establish "did this behaviour change").
//! `SPEC.pgRDF.LIB.v0.6.35-CONSUMER-SCOPE` §0 states the rule this closes:
//! **an emission that exists but is undiscoverable has not shipped.**
//!
//! ## Every known feature gets a row, including the unprobed ones
//!
//! The rows are the SHACL Core surface enumerated from the W3C
//! Recommendation, **not** the set of features that happen to have been
//! measured. That direction is deliberate and is the lesson the harness
//! learned the hard way: it measured 17 of 46 features and reported
//! `not_enforced: []`, which read as a clean bill of health for the whole
//! surface. A consumer counting rows here counts the denominator, so a partial
//! measurement cannot be mistaken for a complete one — anything unmeasured
//! says `unprobed` in the verdict column rather than being absent.
//!
//! ## Both inputs are `include_str!`-ed
//!
//! Following `surface()`: the `.so` can never disagree with the documents it
//! reports, because it carries them. They are generated by
//! `tests/shacl-capability/{run,completeness}.sh` and bound to the engine's own
//! refusal tables by `declared_tables_match_the_measured_capability`, so this
//! is a third *view* of one fact, never a third *statement* of it.

use pgrx::prelude::*;

/// The denominator: SHACL Core as the W3C Recommendation enumerates it.
const SURFACE: &str = include_str!("../tests/shacl-capability/SHACL-CORE-SURFACE.tsv");
/// The measurement: what the probes found on the build that generated it.
const CAPABILITY: &str = include_str!("../tests/shacl-capability/CAPABILITY.json");

/// Which SHACL features `pgrdf.validate` enforces, one row per feature of
/// SHACL Core.
///
/// `verdict` is `enforced`, `not enforced`, or `unprobed`. `mode` is set only
/// where a feature is evaluated by some validation modes and not others —
/// `sh:sparql` is the case, evaluated by `'pgrdf'` and skipped by `'native'`
/// and `'sparql'` — and is NULL otherwise, meaning every mode.
///
/// `measured_on` is the pgRDF version the probes ran against. It is carried per
/// row rather than assumed current: a capability document generated against a
/// different build describes an engine that may no longer exist, which is
/// exactly how a stale document went unnoticed for twelve versions.
#[search_path(pgrdf, pg_temp)]
#[pg_extern]
fn shacl_capability() -> TableIterator<
    'static,
    (
        name!(feature, String),
        name!(kind, String),
        name!(spec_section, String),
        name!(verdict, String),
        name!(mode, Option<String>),
        name!(measured_on, String),
    ),
> {
    let doc: serde_json::Value =
        serde_json::from_str(CAPABILITY).unwrap_or(serde_json::Value::Null);
    let measured_on = doc["pgrdf_version"]
        .as_str()
        .unwrap_or("unknown")
        .to_string();

    let enforced: Vec<&str> = doc["enforced"]
        .as_array()
        .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();
    let not_enforced: Vec<&str> = doc["not_enforced"]
        .as_array()
        .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();
    let mode_only = doc["enforced_only_in_mode"].as_object();

    let rows: Vec<_> = SURFACE
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .map(|l| {
            let mut f = l.splitn(3, '\t');
            let feature = f.next().unwrap_or_default().trim().to_string();
            let section = f.next().unwrap_or_default().trim().to_string();
            let kind = f.next().unwrap_or_default().trim().to_string();

            let mode = mode_only
                .and_then(|m| m.get(&feature))
                .and_then(|v| v.as_str())
                .map(str::to_string);
            // A feature the probes never reached says so. It is never silently
            // reported as enforced, and never omitted.
            let verdict = if mode.is_some() || enforced.contains(&feature.as_str()) {
                "enforced"
            } else if not_enforced.contains(&feature.as_str()) {
                "not enforced"
            } else {
                "unprobed"
            }
            .to_string();

            (feature, kind, section, verdict, mode, measured_on.clone())
        })
        .collect();
    TableIterator::new(rows.into_iter())
}

#[cfg(test)]
mod tests {
    /// The function must report the whole denominator, not the measured subset.
    /// A row count equal to the probe count would mean an unprobed feature had
    /// vanished from the output — the failure this emission exists to prevent.
    #[test]
    fn every_known_feature_gets_a_row() {
        let known = super::SURFACE
            .lines()
            .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
            .count();
        let doc: serde_json::Value = serde_json::from_str(super::CAPABILITY).unwrap();
        assert_eq!(
            known,
            doc["surface_features_known"].as_u64().unwrap() as usize,
            "the TSV and CAPABILITY.json disagree on the size of the surface"
        );
        assert!(known >= 47, "surface unexpectedly small: {known}");
    }

    /// Every feature must resolve to a real verdict. `unprobed` is legitimate
    /// and must be reachable, but it must not be the answer for everything
    /// because the JSON failed to parse.
    #[test]
    fn measurement_parses_and_classifies() {
        let doc: serde_json::Value = serde_json::from_str(super::CAPABILITY).unwrap();
        assert!(doc["enforced"].as_array().is_some_and(|a| !a.is_empty()));
        assert!(doc["pgrdf_version"].as_str().is_some());
    }
}
