-- pgrdf--0.5.1--0.5.39.sql
--
-- No-op upgrade script from v0.5.1 (the only previously-installable
-- version, due to the Cargo.toml-stuck-at-0.5.1 bug surfaced by
-- OCI-GERMINATION on 2026-05-30) to v0.5.39.
--
-- The pgrdf SCHEMA is byte-identical between 0.5.1 and 0.5.39 — every
-- intermediate release (v0.5.2 through v0.5.23) built from the same
-- Cargo.toml version field, so they all shipped the same SQL filename
-- (`pgrdf--0.5.1.sql`) with the same content. The only changes that
-- accrued across those tags were in the .so (TE-5 search_path,
-- TF-* perf measurements, TG-* hygiene, etc.) — none of which alter
-- the SQL surface the dictionary / quads / graphs tables ship.
--
-- v0.5.39 attempted TA-NEW-W: migrate `_pgrdf_dictionary.unique_term`
-- to `UNIQUE NULLS NOT DISTINCT` so `INSERT ... ON CONFLICT DO
-- NOTHING` could dedup NULL-containing dict rows directly (recovering
-- the small perf cost of the `WHERE NOT EXISTS` anti-join introduced
-- in v0.5.37). The migration was code-correct but exposed a PG
-- concurrency hazard: under PG 17 with NULLS NOT DISTINCT, parallel
-- transactions inserting different rows that share an index leaf
-- page deadlock during constraint-check waits. pgrx-parallel test
-- workloads triggered this within seconds; the deadlocks rolled back
-- unrelated tests and turned the suite red. See the v0.5.39 CHANGELOG
-- entry "TA-NEW-W deferred" for the full incident analysis. The
-- schema migration is RE-FILED as a v0.7+ Track-A item gated on
-- either (a) test infrastructure that serialises ingest concurrency
-- or (b) a put_terms_batch retry loop that catches and retries on
-- ERRCODE_T_R_DEADLOCK_DETECTED.
--
-- This script must exist for PostgreSQL to consider the
-- ``ALTER EXTENSION pgrdf UPDATE TO '0.5.39'`` path valid. Its body
-- intentionally has no DDL — declaring the path is sufficient.

-- (no DDL by design)
