-- pgrdf--0.5.1--0.5.42.sql
--
-- No-op upgrade script from v0.5.1 (the only previously-installable
-- version, due to the Cargo.toml-stuck-at-0.5.1 bug surfaced by
-- OCI-GERMINATION on 2026-05-30) to v0.5.42.
--
-- The pgrdf SCHEMA is byte-identical between 0.5.1 and 0.5.42. v0.5.42
-- (TA-4) is a TEST-ONLY release: it adds pgrx-level dict-path matrix
-- parity tests + completes the TriG × 4-paths coverage in the
-- pg_regress gate 132. No runtime or SQL-surface change.
--
-- This script must exist for PostgreSQL to consider the
-- ``ALTER EXTENSION pgrdf UPDATE TO '0.5.42'`` path valid. Its body
-- intentionally has no DDL — declaring the path is sufficient.

-- (no DDL by design)
